"""
scripts/viz/observe_curves.py
=============================
Training curve visualizations from observe/checkpoints/history.json.

OBSERVE is now a KB-augmented OOD classifier (SigLIP-2 + LoRA), so the
metrics tracked per epoch are:

    train: {"loss": float, "top1": float}
    val:   {"loss": float, "top1": float}

Outputs:
  results/figures/observe_curves.png      (loss curves)
  results/figures/observe_top1.png        (top-1 curves)
  plantswarm/latex/auto_observe_curves.tex

Usage:
  python scripts/viz/observe_curves.py --history observe/checkpoints/history.json
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, ROOT)

from scripts.viz._common import (
    ensure_dirs, fig_path, figure_includegraphics, get_mpl,
    have_matplotlib, write_tex,
)


def parse_args():
    p = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    p.add_argument("--history", required=True,
                   help="Path to observe/checkpoints/history.json")
    p.add_argument("--name", default="observe_curves")
    return p.parse_args()


def _train_metric(h: dict, key: str) -> float:
    """Tolerate either {'loss': x, 'top1': y} or legacy {'total': x}."""
    block = h.get("train") or {}
    if key in block:
        return float(block[key])
    # Legacy fallback for older histories.
    if key == "loss" and "total" in block:
        return float(block["total"])
    return 0.0


def _val_metric(h: dict, key: str) -> float:
    block = h.get("val") or {}
    if key in block:
        return float(block[key])
    if key == "loss" and "total" in block:
        return float(block["total"])
    return 0.0


def _plot_loss(plt, history: list, out_png: Path) -> bool:
    if not history:
        return False
    epochs = [h["epoch"] for h in history]
    train  = [_train_metric(h, "loss") for h in history]
    val    = [_val_metric(h,   "loss") for h in history]
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(epochs, train, "o-", label="train", color="#1E88E5")
    ax.plot(epochs, val,   "s-", label="val",   color="#F4511E")
    ax.set_xlabel("Epoch"); ax.set_ylabel("Cross-entropy loss")
    ax.set_title("OBSERVE classification loss (per epoch)")
    ax.legend(); ax.grid(True, alpha=0.3)
    fig.savefig(out_png, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return True


def _plot_top1(plt, history: list, out_png: Path) -> bool:
    if not history:
        return False
    epochs = [h["epoch"] for h in history]
    train  = [_train_metric(h, "top1") for h in history]
    val    = [_val_metric(h,   "top1") for h in history]
    if not any(train) and not any(val):
        return False
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(epochs, train, "o-", label="train", color="#43A047")
    ax.plot(epochs, val,   "s-", label="val",   color="#8E24AA")
    ax.set_xlabel("Epoch"); ax.set_ylabel("Top-1 accuracy")
    ax.set_ylim(0, 1)
    ax.set_title("OBSERVE top-1 accuracy (per epoch)")
    ax.legend(); ax.grid(True, alpha=0.3)
    fig.savefig(out_png, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return True


def _build_tex(name: str, history: list, figures_written: list) -> str:
    lines: list = []
    lines.append(r"% Auto-generated by scripts/viz/observe_curves.py — do not edit by hand.")
    lines.append("")
    if history:
        lines.append(r"\begin{table}[t]")
        lines.append(r"  \centering\small")
        lines.append(r"  \begin{tabular}{rrrrr}")
        lines.append(r"    \toprule")
        lines.append(r"    Epoch & Train loss & Val loss & Train top-1 & Val top-1 \\")
        lines.append(r"    \midrule")
        for h in history:
            tl = _train_metric(h, "loss")
            vl = _val_metric(h,   "loss")
            tt = _train_metric(h, "top1")
            vt = _val_metric(h,   "top1")
            lines.append(
                f"    {h['epoch']} & {tl:.4f} & {vl:.4f} & {tt:.3f} & {vt:.3f} \\\\"
            )
        lines.append(r"    \bottomrule")
        lines.append(r"  \end{tabular}")
        lines.append(r"  \caption{OBSERVE training history (KB-augmented classifier).}")
        lines.append(r"  \label{tab:observe_history}")
        lines.append(r"\end{table}")
        lines.append("")
    for fig_name, caption, label in figures_written:
        lines.append(figure_includegraphics(fig_name, caption, label))
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    ensure_dirs()

    if not Path(args.history).is_file():
        raise SystemExit(f"history not found: {args.history}")

    with open(args.history) as f:
        history = json.load(f)
    if not history:
        raise SystemExit("history.json is empty")

    figures_written: list = []
    if have_matplotlib():
        _, plt = get_mpl()
        for tag, fn, caption, label in [
            ("observe_curves", _plot_loss,
             "OBSERVE classification loss over epochs.",
             "fig:observe_loss"),
            ("observe_top1",   _plot_top1,
             "OBSERVE top-1 accuracy over epochs.",
             "fig:observe_top1"),
        ]:
            out_png = fig_path(tag)
            if fn(plt, history, out_png):
                print(f"  wrote {out_png}")
                figures_written.append((tag, caption, label))
    else:
        print("  matplotlib not installed — table-only output")

    tex_out = write_tex(args.name, _build_tex(args.name, history, figures_written))
    print(f"  wrote {tex_out}")


if __name__ == "__main__":
    main()
