"""
scripts/viz/observe_curves.py
=============================
Training curve visualizations from observe/checkpoints/history.json:

  - train + val total loss per epoch
  - train + val routing accuracy per epoch
  - per-loss-component breakdown

Outputs:
  results/figures/observe_curves.png
  results/figures/observe_loss_components.png
  plantswarm/latex/auto_observe_curves.tex

Usage:
  python scripts/viz/observe_curves.py --history observe/checkpoints/history.json
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, ROOT)

from scripts.viz._common import (
    ensure_dirs, fig_path, figure_includegraphics, get_mpl,
    have_matplotlib, write_tex,
)


def parse_args():
    p = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    p.add_argument("--history", required=True,
                   help="Path to observe/checkpoints/history.json")
    p.add_argument("--name", default="observe_curves")
    return p.parse_args()


def _plot_total_loss(plt, history: list, out_png: Path) -> bool:
    if not history:
        return False
    epochs = [h["epoch"] for h in history]
    train_total = [h["train"].get("total", 0)         for h in history]
    val_total   = [h["val"].get("total",   0)         for h in history]
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(epochs, train_total, "o-", label="train", color="#1E88E5")
    ax.plot(epochs, val_total,   "s-", label="val",   color="#F4511E")
    ax.set_xlabel("Epoch"); ax.set_ylabel("Total loss")
    ax.set_title("OBSERVE multi-task uncertainty loss"); ax.legend()
    ax.grid(True, alpha=0.3)
    fig.savefig(out_png, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return True


def _plot_loss_components(plt, history: list, out_png: Path) -> bool:
    if not history:
        return False
    epochs = [h["epoch"] for h in history]
    keys = ("cal", "cons", "oc")
    colors = {"cal": "#43A047", "cons": "#FB8C00", "oc": "#8E24AA"}
    fig, ax = plt.subplots(figsize=(7, 4))
    for k in keys:
        ys = [h["train"].get(k, 0) for h in history]
        if any(y for y in ys):
            ax.plot(epochs, ys, "o-", label=k, color=colors.get(k))
    ax.set_xlabel("Epoch"); ax.set_ylabel("Component loss (train)")
    ax.set_title("OBSERVE per-component training loss")
    ax.legend(); ax.grid(True, alpha=0.3)
    fig.savefig(out_png, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return True


def _build_tex(name: str, history: list, figures_written: list) -> str:
    lines: list = []
    lines.append(r"% Auto-generated by scripts/viz/observe_curves.py — do not edit by hand.")
    lines.append("")
    if history:
        lines.append(r"\begin{table}[t]")
        lines.append(r"  \centering\small")
        lines.append(r"  \begin{tabular}{rrr}")
        lines.append(r"    \toprule")
        lines.append(r"    Epoch & Train loss & Val loss \\")
        lines.append(r"    \midrule")
        for h in history:
            tt = h["train"].get("total", 0.0)
            vt = h["val"].get("total", 0.0)
            lines.append(
                f"    {h['epoch']} & {tt:.4f} & {vt:.4f} \\\\"
            )
        lines.append(r"    \bottomrule")
        lines.append(r"  \end{tabular}")
        lines.append(r"  \caption{OBSERVE training history.}")
        lines.append(r"  \label{tab:observe_history}")
        lines.append(r"\end{table}")
        lines.append("")
    for fig_name, caption, label in figures_written:
        lines.append(figure_includegraphics(fig_name, caption, label))
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    ensure_dirs()

    if not Path(args.history).is_file():
        raise SystemExit(f"history not found: {args.history}")

    with open(args.history) as f:
        history = json.load(f)
    if not history:
        raise SystemExit("history.json is empty")

    figures_written: list = []
    if have_matplotlib():
        _, plt = get_mpl()
        for tag, fn, caption, label in [
            ("observe_main",       _plot_total_loss,
             "OBSERVE multi-task uncertainty loss over epochs.",
             "observe_curves"),
            ("observe_components", _plot_loss_components,
             "OBSERVE per-component training loss.",
             "observe_components"),
        ]:
            out_png = fig_path(tag)
            if fn(plt, history, out_png):
                print(f"  wrote {out_png}")
                figures_written.append((tag, caption, label))
    else:
        print("  matplotlib not installed — table-only output")

    tex_out = write_tex(args.name, _build_tex(args.name, history, figures_written))
    print(f"  wrote {tex_out}")


if __name__ == "__main__":
    main()
